version: '3'

services:
    brevetsapp:
        build: brevets/.
        command: flask_brevets.py
        ports: 
          - "5001:5000"
        environment:
            MONGODB_HOSTNAME: brevetsdb
    brevetsdb:
        image: mongo:latest
        depends_on:
            - brevetsapp
